"""TC-S001-F-007-06 — Manifest reconciliation produces six fresh entries.

After reset_case_to_seed runs, document_manifest.json should contain exactly
six entries for the case (one per seed file) with non-empty documentId and
fileHash values that were generated by the reconcile() pass.
"""

from __future__ import annotations

import json


def test_manifest_has_six_fresh_entries_for_case(session_sandbox):
    sm = session_sandbox["session_manager"]
    case_id = session_sandbox["case_id"]
    manifest_path = session_sandbox["manifest_path"]

    sm.reset_case_to_seed(case_id)

    assert manifest_path.exists(), "manifest file must be written by the reset flow"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    case_docs = [d for d in manifest["documents"] if d.get("caseId") == case_id]
    assert len(case_docs) == 6, (
        f"Expected exactly 6 manifest entries for {case_id}, "
        f"got {len(case_docs)}: {[d.get('fileName') for d in case_docs]}"
    )

    expected_files = {
        "Aufenthalstitel.png",
        "Geburtsurkunde.jpg",
        "Personalausweis.png",
        "Sprachzeugnis-Zertifikat.pdf",
        "Anmeldeformular.pdf",
        "Notenspiegel.pdf",
    }
    seen_files = {d["fileName"] for d in case_docs}
    assert seen_files == expected_files, (
        f"Manifest filenames mismatch. expected={expected_files}, got={seen_files}"
    )

    for doc in case_docs:
        assert doc.get("documentId"), f"missing documentId on {doc.get('fileName')}"
        assert doc.get("fileHash"), f"missing fileHash on {doc.get('fileName')}"
